server:
  port: 8088
spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - AddRequestHeader=X-Requested-By, API_GATEWAY   
            - AddResponseHeader=X-Gateway, SpringCloudGateway
        - id: secured-service
          uri: http://localhost:8082
          predicates:
            - Path=/matches/**
          filters:
            - AddRequestHeader=X-Requested-By, API_GATEWAY
            - AddResponseHeader=X-Gateway, SpringCloudGateway
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com:
      example:
        gateway: DEBUG
